### ISSUE TITLE
Change archive strategie for RKI

### ISSUE THREAD

**Issue by lekroll** [zidatalab/covid19dashboard#37]
Pls, do not create seperate tables for each day... Use this: https://stackoverflow.com/questions/26568182/is-it-possible-to-insert-add-a-row-to-a-sqlite-db-table-using-dplyr-package and append current rki table into rkiarchive table...

**Comment by edg-stg** [comment]
wouldn't it take too long to filter and load the data for a specific publication date? like: tbl(conn, "rkiarchive") %>% filter(rkidate==wunschdate) %>% collect()
at the moment, even loading one day takes a few minutes without the filtering: tbl(conn, "rki_2020-11-30") %>% collect()

**Comment by lekroll** [comment]
Not if we set an index for date

**Comment by lekroll** [comment]
Can be done via pgadmin connection to DB, I can do it if needed, you just need to clean up. I think the appropriate field is Datenstand?
